### ISSUE TITLE
Move some set_fact to vars/main.yml

### ISSUE THREAD

**Issue by robertdebock** [d4gh0s7/postgres_dump#18]
You've got some `set_fact` tasks like:

```
- name: Determine the postgresql dump file name
  set_fact: postgresql_dump_filename=full_dump-{{ ansible_date_time.iso8601_basic_short }}.sql
```

That can be moved to `vars/main.yml`, like this:
```
postgresql_dump_filename: "full_dump-{{ ansible_date_time.iso8601_basic_short }}.sql"
```

This keeps the tasks as clean as possible.

And if you need to use set_facts, you can combine all facts into a single set_facts tasks, like so:
```
- name: do something
  set_fact:
    variable1: value1
    variable2: value2
```

(See how I did not use the `=` there? ;-) )
