### ISSUE TITLE
README contains a strange example

### ISSUE THREAD

**Issue by robertdebock** [d4gh0s7/postgres_dump#20]
The readme now states:

```
  vars_files:
    - ./group_vars/all.yml
```

But, `group_vars/all.yml` will always be used, no need to include it.

If you want to tell users that there are variables, you can use a couple of formats that are easy to read:

In a vars structure:
```
  vars:
    variable1: value1
    variable2: value2
```

Or on inclusion of the role:
```
  roles:
    - role: myroles
      variable1: value1
      variable2: values2
```
